### PR TITLE
Fix client capability for semantic tokens

### PR DESCRIPTION
**Pull request by markdumay**
First of all, great to see you guys are making the effort to port the LSP specification to Go. I started experimenting with your package quite recently. I encountered a small problem when trying to unmarshal the `InitializeParams` as generated by `vscode-languageclient` with version `7.0.0`. VSCode generates the client capabilities automatically, but handling the payload of `InitializeParams` on the server side (written in Go using your protocol package) gives the following error:

```
Message: json: cannot unmarshal object into Go struct field SemanticTokensWorkspaceClientCapabilitiesRequests.capabilities.textDocument.semanticTokens.requests.full of type bool
```

It seems the following section of the `InitializeParams` JSON is the cause of the issue.
```
[...]
    "textDocument": {
      "semanticTokens": {
        "requests": {
          "range": true,
          "full": {
            "delta": true
          }
      }
    }
[...]
```

According to the official [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#semanticTokensClientCapabilities), the value for `full` can be either `boolean` or another embedded struct. 

This PR fixes the issue by adjusting the struct `SemanticTokensWorkspaceClientCapabilitiesRequests` in `capabilities_client.go`. It simply changes the type of `Full` from `bool` to `interface{}`. Let me know if you need more evidence or supporting files to reproduce the error.

### CODE REVIEW

**Comment by zchee** [comment]
@markdumay Thanks for contributing!
I understand you said problem and approve this change.
But I forgotten enabled run forked pull request on CircleCI. I'll dig CircleCI docs, but could you amend and force push this branch?
Thanks.

**Comment by markdumay** [comment]
Great, good to hear you approve the proposed change. I made a small documentation change and submitted a force push. It seems this has triggered the CircleCI workflows. There is now an error though:

```
./capabilities_client_gojay.go:1824: cannot use v.Full (type interface {}) as type bool in argument to enc.BoolKeyOmitEmpty: need type assertion
./capabilities_client_gojay.go:1836: cannot use &v.Full (type *interface {}) as type *bool in argument to dec.Bool
WARN invalid TestEvent: FAIL	go.lsp.dev/protocol [build failed]
```

It looks like the `capabilities_client_gojay.go` file is out of sync. Is there a specific command that you run to regenerate the `gojay` files?

**Comment by zchee** [comment]
@markdumay sorry for late, I'll comment later, maybe ~6h.

**Comment by zchee** [comment]
@markdumay Unfortunately, the gojay bindings are written by my hand.

Could you patch the below diff? It should work.

```diff
diff --git a/capabilities_client_gojay.go b/capabilities_client_gojay.go
index 3c2be32..759d87a 100644
--- a/capabilities_client_gojay.go
+++ b/capabilities_client_gojay.go
@@ -1821,7 +1821,7 @@ var (
 // MarshalJSONObject implements gojay.MarshalerJSONObject.
 func (v *SemanticTokensWorkspaceClientCapabilitiesRequests) MarshalJSONObject(enc *gojay.Encoder) {
 	enc.BoolKeyOmitEmpty(keyRange, v.Range)
-	enc.BoolKeyOmitEmpty(keyFull, v.Full)
+	enc.AddInterfaceKey(keyFull, v.Full)
 }
 
 // IsNil implements gojay.MarshalerJSONObject.
@@ -1833,7 +1833,7 @@ func (v *SemanticTokensWorkspaceClientCapabilitiesRequests) UnmarshalJSONObject(
 	case keyRange:
 		return dec.Bool(&v.Range)
 	case keyFull:
-		return dec.Bool(&v.Full)
+		return dec.Interface(&v.Full)
 	}
 	return nil
 }
```

**Comment by markdumay** [comment]
Thanks @zchee, I force pushed the changes. CircleCI now indicates I'm not authorized to run the workflows though.

**Review by zchee — APPROVED** [review]

**Comment by zchee** [comment]
@markdumay merged. Thanks contribute!

**Comment by zchee** [comment]
@markdumay also released a new tag.

https://github.com/go-language-server/protocol/releases/tag/v0.11.2

**Comment by markdumay** [comment]
Great, glad to help. Keep up the good work!

**Pull request merged**
